/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sasistencia;

import java.awt.ScrollPane;
import java.awt.TextArea;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author final
 */
public class Incidencias extends javax.swing.JFrame {
Conectar cc=new Conectar();
Connection cn= cc.conexion();
int clv;
    /**
     * Creates new form Incidencias
     */
    public Incidencias() {
        initComponents();
      TableColumnModel mod = TabJust.getColumnModel();
      mod.getColumn(0).setPreferredWidth(130);
      mod.getColumn(1).setPreferredWidth(450);
      mod.getColumn(2).setPreferredWidth(130);
      SPNom.setVisible(false);     
      btnInsert.setVisible(false);
      btnCancel.setVisible(false);
      llenar();
      listJust();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnMod = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtAnuncio = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        bntNew = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        Tab = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtDesc = new javax.swing.JTextArea();
        cmbEstad = new javax.swing.JComboBox<>();
        btnInsert = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabJust = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListJust = new javax.swing.JList<>();
        jPanel17 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        SPNom = new javax.swing.JScrollPane();
        TabNom = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DateChIn = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtClavEmp = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        btnMod.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btnMod);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 141, 117));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Justificantes");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 141, 117)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(19, 141, 117));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnuncio.setEditable(false);
        txtAnuncio.setBackground(new java.awt.Color(19, 141, 117));
        txtAnuncio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAnuncio.setForeground(new java.awt.Color(255, 255, 255));
        txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel9.add(txtAnuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 30, 309, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 310, 240));

        jPanel10.setBackground(new java.awt.Color(19, 141, 117));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(19, 141, 117));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel11.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 270, 60));

        bntNew.setBackground(new java.awt.Color(255, 255, 255));
        bntNew.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bntNew.setForeground(new java.awt.Color(102, 102, 102));
        bntNew.setText("Nuevo");
        bntNew.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        bntNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNewActionPerformed(evt);
            }
        });
        jPanel11.add(bntNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 270, 60));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 102, 102));
        btnBack.setText("Regresar");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel11.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 270, 60));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 285, 270));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 310, 330));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        Tab.setBackground(new java.awt.Color(255, 255, 255));
        Tab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        Tab.setForeground(new java.awt.Color(19, 141, 117));
        Tab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabMouseClicked(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(32, 64, 81));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(19, 141, 117));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Generar Tipos de Justificantes");
        jPanel16.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 360, -1));

        jPanel19.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 30));

        jPanel7.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 3, true), "Descripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(19, 141, 117));
        jLabel17.setText("Descripción del justificantes");
        jPanel20.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));

        TxtDesc.setBackground(new java.awt.Color(255, 255, 255));
        TxtDesc.setColumns(20);
        TxtDesc.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        TxtDesc.setForeground(new java.awt.Color(51, 51, 51));
        TxtDesc.setRows(5);
        TxtDesc.setBorder(null);
        jScrollPane2.setViewportView(TxtDesc);

        jPanel20.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, -1));

        cmbEstad.setBackground(new java.awt.Color(255, 255, 255));
        cmbEstad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cmbEstad.setForeground(new java.awt.Color(51, 51, 51));
        cmbEstad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\tActivo", "\tDesactivado" }));
        jPanel20.add(cmbEstad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 160, -1));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(19, 141, 117));
        btnInsert.setText("Actualizar");
        btnInsert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel20.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 100, 40));

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(19, 141, 117));
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel20.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 100, 40));

        jPanel7.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 640, 160));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));

        TabJust.setBackground(new java.awt.Color(255, 255, 255));
        TabJust.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        TabJust.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TabJust.setForeground(new java.awt.Color(0, 0, 0));
        TabJust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Descripción", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabJust.setComponentPopupMenu(jPopupMenu1);
        TabJust.setGridColor(new java.awt.Color(255, 255, 255));
        TabJust.setRowHeight(18);
        TabJust.setRowMargin(2);
        TabJust.setSelectionBackground(new java.awt.Color(19, 141, 117));
        TabJust.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TabJust.setSurrendersFocusOnKeystroke(true);
        jScrollPane3.setViewportView(TabJust);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 710, 260));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sasistencia/LogBonton/boton-actualizar_2.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 50, 40));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(19, 141, 117));
        jLabel18.setText("Justificantes Guardados");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        Tab.addTab("Justificantes", jPanel7);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Tipo de justificante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(19, 141, 117))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        ListJust.setBackground(new java.awt.Color(255, 255, 255));
        ListJust.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ListJust.setForeground(new java.awt.Color(51, 51, 51));
        ListJust.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListJust.setSelectionBackground(new java.awt.Color(19, 141, 117));
        ListJust.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ListJust);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 230));

        jPanel15.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 270, 280));

        jPanel17.setBackground(new java.awt.Color(32, 64, 81));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(19, 141, 117));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Justificar Incidencias");
        jPanel13.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, -1));

        jPanel17.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 30));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Nombre de Empleado");
        jPanel15.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel15.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 360, 30));

        SPNom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));

        TabNom.setBackground(new java.awt.Color(255, 255, 255));
        TabNom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TabNom.setForeground(new java.awt.Color(102, 102, 102));
        TabNom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabNom.setEditingColumn(0);
        TabNom.setGridColor(new java.awt.Color(255, 255, 255));
        TabNom.setRowHeight(18);
        TabNom.setRowMargin(2);
        TabNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabNomMouseClicked(evt);
            }
        });
        SPNom.setViewportView(TabNom);

        jPanel15.add(SPNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 360, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Día a justificar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Fecha:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 30));

        DateChIn.setBackground(new java.awt.Color(255, 255, 255));
        DateChIn.setForeground(new java.awt.Color(51, 51, 51));
        DateChIn.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel6.add(DateChIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 200, -1));

        jPanel15.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 500, 130));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Clave de empleado");
        jPanel15.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, 30));

        txtClavEmp.setEditable(false);
        txtClavEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtClavEmp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClavEmp.setForeground(new java.awt.Color(51, 51, 51));
        txtClavEmp.setBorder(null);
        jPanel15.add(txtClavEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 105, 170, 24));
        jPanel15.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 170, 20));

        Tab.addTab("Justificar incidencias", jPanel15);

        jPanel1.add(Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 840, 570));

        jPanel18.setBackground(new java.awt.Color(32, 64, 81));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(19, 141, 117));
        jPanel14.setForeground(new java.awt.Color(19, 141, 117));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Anuncios");
        jPanel14.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 130, 30));

        jPanel18.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 270, 40));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 310, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      if(Tab.getSelectedIndex()==0){
      if(vacio2(TxtDesc,jScrollPane2)!=true){
          anuncio("",false);
          int clv=genC(); 
          if(clv!=0){
            anuncio("",false);
           String stat="";
           String sql="INSERT INTO `dbregasi`.`cjusasi` (`NIDTPJU`, `CDESJUS`, `CSTATUS`, `CUSUINS`, `DFECINS`, `CUSUMOD`, `DFECMOD`) VALUES (?,?,?,?,?,?,?);";
        try{
        PreparedStatement pst;
        pst=cn.prepareStatement(sql);          
            pst.setInt(1, clv);
            pst.setString(2,TxtDesc.getText());
            if(cmbEstad.getSelectedIndex()==0){
               stat="A"; 
            }else{stat="D";}
            pst.setString(3,stat);
            pst.setInt(4,3);
            pst.setString(5,fechaAct());
            pst.setInt(6,3);
            pst.setString(7,fechaAct());
            pst.executeUpdate();
            pst.close();
            anuncio("Justificante guardado",true);
    }catch(SQLException ex){      
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
        anuncio("Error al cargar datos",true);
        JOptionPane.showMessageDialog(null,ex);
    }
          }else{anuncio("Erro al generar clave",true);}
      }else{anuncio("por favor llene los recuadors marcados",true);}
      }else
          if(Tab.getSelectedIndex()==1){
              Save();
          }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(txtBuscar.getText().equals("")){
            SPNom.setVisible(false);
        }
        else{
            SPNom.setVisible(true);
            String [] t = {"","",""};
            String nom="",ap="";         
            DefaultTableModel m = new DefaultTableModel(null,t);
            ResultSet rs;
            Statement st;
            String [] nombre = new String [3];
            try{
                String sql="SELECT CNOMBRE, CAPEUNO, CAPEDOS FROM ddatemp WHERE CNOMBRE like '%"+txtBuscar.getText()+"%'";
                //JOptionPane.showMessageDialog(null,sql);
                st=(Statement) cn.createStatement();
                rs=st.executeQuery(sql);
                while(rs.next())
                {
                    nombre[0]=rs.getString(1);
                    nombre[1]=rs.getString(2);
                    nombre[2]=rs.getString(3);
                    m.addRow(nombre);
                }
                TabNom.setEditingRow(-1);
                TabNom.setModel(m);
                rs.close();
                int x = m.getRowCount();
                int y = 20+x*18;
                SPNom.setSize(360,y);
                int height = SPNom.getSize().height;
                if(height>=120){
                    SPNom.setSize(360,120);
                }
            }catch(SQLException ex){
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void TabNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabNomMouseClicked
        DefaultTableModel m = new DefaultTableModel();
        m=(DefaultTableModel) TabNom.getModel();
        int row =m.getRowCount();
        int height = SPNom.getSize().height;
        int y = 20+row*18;
        SPNom.setSize(360,y );
        if(height>=125){
            SPNom.setSize(360,125);
        }
        SPNom.setVisible(false);
        if(TabNom.getSelectedRow()!=-1){
            anuncio("",false);
            String Nombre,Ap1,Ap2;
            Nombre=String.valueOf(m.getValueAt(TabNom.getSelectedRow(),0));
            Ap1=String.valueOf(m.getValueAt(TabNom.getSelectedRow(),1));
            Ap2=String.valueOf(m.getValueAt(TabNom.getSelectedRow(),2));
            txtBuscar.setText(Nombre+" "+Ap1+" "+Ap2);
          String sql ="SELECT CCVEEMP FROM ddatemp WHERE CNOMBRE ='"+Nombre+"' and CAPEUNO = '"+Ap1+"'AND CAPEDOS ='"+Ap2+"'";
           ResultSet rs=consultaG(sql);
       try{
           while(rs.next()){
             txtClavEmp.setText(rs.getString(1));
           }
       }catch(SQLException ex){
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);           
        }
        }
        else{anuncio("Elija un elemento de la tabla",true);}
    }//GEN-LAST:event_TabNomMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      DefaultTableModel m = (DefaultTableModel) TabJust.getModel();
      while(m.getRowCount()>0){
          m.removeRow(0);
      }
      llenar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bntNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNewActionPerformed
        DefaultTableModel m = (DefaultTableModel) TabJust.getModel();
      while(m.getRowCount()>0){
          m.removeRow(0);
      }
      llenar();
      TxtDesc.setText("");
      txtBuscar.setText("");
      txtClavEmp.setText("");
      anuncio("",false);
    }//GEN-LAST:event_bntNewActionPerformed

    private void TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabMouseClicked
        if(Tab.getSelectedIndex()==1){
            listJust();
        }
        anuncio("",false);
    }//GEN-LAST:event_TabMouseClicked

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
         DefaultTableModel m = (DefaultTableModel) TabJust.getModel();
         int row=TabJust.getSelectedRow();
        if(row!=-1){
            anuncio("Modificando registro",true);
            btnInsert.setVisible(true);
            btnCancel.setVisible(true);
            btnGuardar.setEnabled(false);
            bntNew.setEnabled(false);
            btnBack.setEnabled(false);
            TxtDesc.setText(m.getValueAt(row,1).toString());
            if(m.getValueAt(row,2).toString().equals("A")){
                cmbEstad.setSelectedIndex(0);
                clv=Integer.parseInt(m.getValueAt(row,0).toString());
            }else{
                cmbEstad.setSelectedIndex(1);
            }                      
        }else{
            anuncio("justificante no seleccionado",true);
        }    
        
    }//GEN-LAST:event_btnModActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if(vacio2(TxtDesc,jScrollPane2)!=true){
             anuncio(null,false);
             String stat="";
              if(cmbEstad.getSelectedIndex()==0){
               stat="A"; 
            }else{stat="D";}
            String sql ="UPDATE cjusasi SET `CDESJUS` = '"+TxtDesc.getText()+"', `CSTATUS` = '"+stat+"', `CUSUMOD` = '"+4+"', `DFECMOD` = '"+fechaAct()+"' WHERE NIDTPJU = '"+clv+"';";
            if(update(sql)){
                anuncio("Justificante actualizado",true);
                  DefaultTableModel m = (DefaultTableModel) TabJust.getModel();
                while(m.getRowCount()>0){
                    m.removeRow(0);
                }
                llenar();
              btnInsert.setVisible(false);
            btnCancel.setVisible(false);
            btnGuardar.setEnabled(true);
            bntNew.setEnabled(true);
            btnBack.setEnabled(true);
             TxtDesc.setText("");
        cmbEstad.setSelectedIndex(0);
            }else{ anuncio("Error al actulizar",true);
            }
        }else{
             anuncio("por favor llene los recuadros ",true);
        }
        
        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        TxtDesc.setText("");
        cmbEstad.setSelectedIndex(0);
        btnInsert.setVisible(false);
            btnCancel.setVisible(false);
            btnGuardar.setEnabled(true);
            bntNew.setEnabled(true);
            btnBack.setEnabled(true);
            anuncio("",false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incidencias().setVisible(true);
            }
        });
    }

    public  ResultSet consultaG(String sql){
          ResultSet rs;
        Statement st;
        try{
         st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        return rs;
        }catch(SQLException ex){
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
             return null;
        }       
    }
    public void anuncio(String men, boolean mos){         
       if(mos == true){
            txtAnuncio.setText(men);            
             txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
           }
       else {
     txtAnuncio.setText("");
      txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true)); // blanco
       }       
   }
    public void llenar(){
        String row[] = new String[3];
        DefaultTableModel m = (DefaultTableModel) TabJust.getModel();
         ResultSet rs=consultaG("SELECT nidtpju,cdesjus,cstatus FROM `cjusasi`");
        try{
           while(rs.next()){
            row[0]=String.valueOf(rs.getInt(1));
            row[1]=rs.getString(2);
            row[2]=rs.getString(3);
            m.addRow(row);
           }            
        }catch(SQLException ex){
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);             
        }              
    }
    public boolean vacio(JTextField x){    
     if(x.getText().length()==0){
           x.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
        return true;
        }else
         x.setBorder(null);
     return false;
    }
     public boolean vacio2(JTextArea x, JScrollPane y){    
     if(x.getText().length()==0){
           y.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
        return true;
        }else
         y.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19,141,117), 2, true)); 
     return false;
    }
     public int genC(){
         int clv=0;
             ResultSet rs=consultaG("SELECT NIDTPJU FROM cjusasi ORDER BY NIDTPJU DESC LIMIT 1");
              try{
           while(rs.next()){
            clv=rs.getInt(1);
           }
           clv++;
           return clv;
        }catch(SQLException ex){
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);             
            return 0;
        }                      
     }
      public String fechaAct(){
     Date fecha = new Date();
     SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
     return formato.format(fecha);
      }
      public void listJust(){
          DefaultListModel m = new DefaultListModel();
          ListJust.setModel(m);
          String row ="";
          ResultSet rs = consultaG("SELECT nidtpju,cdesjus from cjusasi where cstatus = 'A' order by nidtpju asc");
         try{
           while(rs.next()){
            row=rs.getString(1);
            row+=" "+rs.getString(2);
            m.addElement(row);
            row="";
           }
          
        }catch(SQLException ex){
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);             
            
        }                      
      }
      public void Save(){
          if(vacio(txtClavEmp)!=true){
              anuncio("",false);
              if(ListJust.getSelectedIndex()!=-1){
                  String fecha =formatoFecha();               
                  jScrollPane1.setBorder(null);
                  if(fecha.equals("")!=true){
                  DefaultListModel m = (DefaultListModel)ListJust.getModel();
                  String sql="INSERT INTO pjusasi (`CCVEEMP`, `DFECINC`, `NIDTPJU`, `CSTATUS`, `CUSUINS`, `DFECINS`, `CUSUMOD`, `DFECMOD`) VALUES (?,?,?,?,?,?,?,?);";                 
                try{                    
                     PreparedStatement pst;
                     pst=cn.prepareStatement(sql);          
                     pst.setString(1,txtClavEmp.getText());
                     pst.setString(2,fecha);
                     String[] partes =m.getElementAt(ListJust.getSelectedIndex()).toString().split(" ");
                     pst.setString(3,partes[0]);
                     pst.setString(4,"A");
                     pst.setInt(5,3);
                     pst.setString(6,fechaAct());
                     pst.setInt(7,3);
                     pst.setString(8,fechaAct());
                     pst.executeUpdate();
                     pst.close();
                     anuncio("Justificante aplicado",true);
                    }catch(SQLException ex){      
                        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
                        anuncio("Justificante duplicado // problemas con la base",true);
                    } }                                                       
              }else{anuncio("Seleccione un tipo de justificante",true);
              jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true));
              }
          }else{anuncio("por favor llene los recuadros marcados",true);}
      }
      public String formatoFecha(){
        if(DateChIn.getDate()!=null){
          anuncio("",false);
          DateChIn.setBorder(null);      
      String fecha="";  
      SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd");
     // Calendar cal = Calendar.getInstance();
        fecha+=DateChIn.getCalendar().get(Calendar.YEAR)+"-";
        fecha+=(DateChIn.getCalendar().get(Calendar.MONTH)+1)+"-";
        fecha+=DateChIn.getCalendar().get(Calendar.DAY_OF_MONTH);
     try {
         Date fech = form.parse(fecha);
         return form.format(fech);
     } catch (ParseException ex) {
         Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);        
     }
       
      }else{
          DateChIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true));
          anuncio("Fecha no ingresada",true); 
          return "";}
       return "";
   }
       public boolean update(String sql){
       try{
    PreparedStatement pst = cn.prepareStatement(sql);
    pst.executeUpdate();
    pst.close();
    return true;
    }catch(SQLException ex){
       Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex); 
       return false;
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChIn;
    private javax.swing.JList<String> ListJust;
    private javax.swing.JScrollPane SPNom;
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JTable TabJust;
    private javax.swing.JTable TabNom;
    private javax.swing.JTextArea TxtDesc;
    private javax.swing.JButton bntNew;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInsert;
    private javax.swing.JMenuItem btnMod;
    private javax.swing.JComboBox<String> cmbEstad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JTextField txtAnuncio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtClavEmp;
    // End of variables declaration//GEN-END:variables
}
