/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sasistencia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author final
 */
public class ModFecha extends javax.swing.JFrame {
Conectar cc=new Conectar();
Connection cn= cc.conexion();
    /**
     * @return the estad
     */

     String fecha, motivo;
    /**
     * @param estad the estad to set
     */
    /*public void setEstad(boolean estad) {
        this.estad = estad;
    }*/
  

    /**
     * Creates new form ModFecha
     */
    public ModFecha(String fecha,String motivo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fecha=fecha;
        this.motivo=motivo;
        TxtFecha.setText(this.fecha);
        TxtMot.setText(this.motivo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtMot = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        cmbEstad = new javax.swing.JComboBox<>();
        btnInsert = new javax.swing.JButton();
        btnInsert1 = new javax.swing.JButton();
        TxtFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 141, 117));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar día no laborable");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 370, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 40));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(19, 141, 117));
        jLabel17.setText("Fecha:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(19, 141, 117));
        jLabel18.setText("Motivo:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 30));

        TxtMot.setBackground(new java.awt.Color(255, 255, 255));
        TxtMot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtMot.setBorder(null);
        jPanel1.add(TxtMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 330, 20));

        jSeparator8.setBackground(new java.awt.Color(19, 141, 117));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 330, 10));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(19, 141, 117));
        jLabel16.setText("Estado:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 30));

        cmbEstad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Desactivado" }));
        cmbEstad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEstad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 30));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(19, 141, 117));
        btnInsert.setText("Aceptar");
        btnInsert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, 40));

        btnInsert1.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnInsert1.setForeground(new java.awt.Color(19, 141, 117));
        btnInsert1.setText("Cancelar");
        btnInsert1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 100, 40));

        TxtFecha.setEditable(false);
        TxtFecha.setBackground(new java.awt.Color(255, 255, 255));
        TxtFecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtFecha.setForeground(new java.awt.Color(0, 0, 0));
        TxtFecha.setBorder(null);
        jPanel1.add(TxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 67, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
     if(vacio(TxtMot)!=true){
      String status ="";
     if(cmbEstad.getSelectedIndex()==0){
         status="A";
     }else{status="D";}
        String sql="UPDATE `dbregasi`.`mdiasnl` SET `CMOTIVO` = '"+TxtMot.getText()+"', `CSTATUS` = '"+status+"' WHERE `mdiasnl`.`DFECHNL` = '"+TxtFecha.getText()+"';";
        if(update(sql)==true){
            JOptionPane.showMessageDialog(rootPane,"Fecha Actializada");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane,"Error al actualizar");
        }
    }//GEN-LAST:event_btnInsertActionPerformed
    }
    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnInsert1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModFecha(null,null).setVisible(true);
                
            }
        });
    }
    public boolean update(String sql){
       try{
    PreparedStatement pst = cn.prepareStatement(sql);
    pst.executeUpdate();
    pst.close();
    return true;
    }catch(SQLException ex){
       Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex); 
       return false;
    }
    }
     public boolean vacio(JTextField x){    
     if(x.getText().length()==0){
           x.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
        return true;
        }else
         x.setBorder(null);
     return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtMot;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JComboBox<String> cmbEstad;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
