/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sasistencia;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author final
 */
public class UpLoad extends javax.swing.JFrame implements Runnable {
     Conectar cc=new Conectar();
Connection cn= cc.conexion();
    Thread hilo;
    int bandera=0;
     String hora,minutos,segundos,hour,ruta,txt;
    public UpLoad() {
        initComponents();
        txtFecha.setText(fecha());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
        txtFecha.setEditable(false);
        txtHora.setEditable(false);
        txtException.setEditable(false);
         TxtRegC.setEditable(false);
         TxtRegG.setEditable(false);
         TxtRegX.setEditable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtException = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabRegA = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtAnuncio = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        BtnCargar1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtRegX = new javax.swing.JTextField();
        TxtRegC = new javax.swing.JTextField();
        TxtRegG = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(19, 141, 117));
        jPanel10.setForeground(new java.awt.Color(19, 141, 117));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Registro De Asistencia");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(19, 141, 117));
        jLabel6.setText("Estado del Archivo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 150, 30));

        txtException.setBackground(new java.awt.Color(255, 255, 255));
        txtException.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtException.setForeground(new java.awt.Color(0, 0, 0));
        txtException.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jPanel1.add(txtException, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 350, 25));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jScrollPane1.setForeground(new java.awt.Color(19, 141, 117));
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        TabRegA.setBackground(new java.awt.Color(255, 255, 255));
        TabRegA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        TabRegA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TabRegA.setForeground(new java.awt.Color(0, 0, 0));
        TabRegA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "	Clave del Empleado", "Fecha del registro", "Hora del registro", "Num. Equipo", "Estado del registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabRegA.setGridColor(new java.awt.Color(19, 141, 117));
        TabRegA.setInheritsPopupMenu(true);
        TabRegA.setRowHeight(18);
        TabRegA.setRowMargin(2);
        TabRegA.setSelectionBackground(new java.awt.Color(19, 141, 117));
        TabRegA.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TabRegA.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TabRegA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 820, 290));

        jPanel4.setBackground(new java.awt.Color(19, 141, 117));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Anuncios");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 141, 117)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(19, 141, 117));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnuncio.setBackground(new java.awt.Color(19, 141, 117));
        txtAnuncio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAnuncio.setForeground(new java.awt.Color(255, 255, 255));
        txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel9.add(txtAnuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 30));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 320, 60));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 190));

        jPanel12.setBackground(new java.awt.Color(19, 141, 117));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(19, 141, 117));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel13.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 270, 60));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Nuevo");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 270, 60));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Regresar");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 270, 60));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 285, 270));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 320, 310));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 141, 117));
        jLabel7.setText("Registros cancelados");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, 160, 30));

        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(19, 141, 117));
        jLabel8.setText("Hora:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 70, 30));

        txtHora.setBackground(new java.awt.Color(255, 255, 255));
        txtHora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 160, 30));

        BtnCargar1.setBackground(new java.awt.Color(255, 255, 255));
        BtnCargar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnCargar1.setForeground(new java.awt.Color(102, 102, 102));
        BtnCargar1.setText("Cargar Archivo");
        BtnCargar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 3, true));
        BtnCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCargar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 200, 60));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(19, 141, 117));
        jLabel9.setText("Fecha:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 70, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(19, 141, 117));
        jLabel10.setText("Registros Cargados");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 150, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(19, 141, 117));
        jLabel11.setText("Registros Guardados");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 150, 30));

        TxtRegX.setBackground(new java.awt.Color(255, 255, 255));
        TxtRegX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtRegX.setForeground(new java.awt.Color(0, 0, 0));
        TxtRegX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jPanel1.add(TxtRegX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 100, 30));

        TxtRegC.setBackground(new java.awt.Color(255, 255, 255));
        TxtRegC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtRegC.setForeground(new java.awt.Color(0, 0, 0));
        TxtRegC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jPanel1.add(TxtRegC, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 100, 30));

        TxtRegG.setBackground(new java.awt.Color(255, 255, 255));
        TxtRegG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtRegG.setForeground(new java.awt.Color(0, 0, 0));
        TxtRegG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jPanel1.add(TxtRegG, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      DefaultTableModel m = new DefaultTableModel();
        m=(DefaultTableModel)TabRegA.getModel();
        String clv,fecha,estado;
        int Clave;
        String HoraES []= new String [2];
        String HoraR []= new String [2];
        if(m.getRowCount()!=0){
            anuncio("",false);  
            if(bandera!=1){
                anuncio("",false); 
                InsertD();
                Motor mr = new Motor();
                for(int i=0;i<m.getRowCount();i++){
                    clv=m.getValueAt(i,0).toString();
                    Clave=Integer.parseInt(m.getValueAt(i,0).toString());
                    fecha=m.getValueAt(i,1).toString();
                    estado=m.getValueAt(i,4).toString();                   
                    if(Dif(i,clv,fecha)==false && estado.equals("Cargado")){                        
                       if(NoIgual(i,fecha,1)!=true) {
                         mr.FalT(fecha); // parametro fecha
                       }
                      try {
                            HoraES=mr.getHoraES(Clave,fecha); // clave y fecha -> Hora de entra y salida
                            HoraR=mr.getHoraReg(Clave,fecha); // clave y fecha -> Hora en la que registro Entrada y Salida
                            //JOptionPane.showMessageDialog(null,HoraES[0]+" // "+HoraES[1]);
                             //JOptionPane.showMessageDialog(null,HoraR[0]+" // "+HoraR[1]);
                            if(HoraR[1].equals("false")!=true){
                                mr.SalInc(HoraR[1],HoraES[1]+":00",Clave,fecha);
                            }
                            mr.EnInc(HoraES[0]+":00",Clave,HoraR[0],fecha);
                            
                        } catch (ParseException ex) {
                            Logger.getLogger(UpLoad.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    
                }
               
            }else{anuncio("Archivo no compatible",true);  }
                
     }else{ anuncio("No ha cargo ningun registor en la tabla",true);  }
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiarTabla();
        TxtRegC.setText("");
           TxtRegG.setText("");
           TxtRegX.setText("");
           txtException.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void BtnCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargar1ActionPerformed
       JFileChooser sec = new JFileChooser();
       sec.showOpenDialog(this);
       //File arch = sec.getSelectedFile();
       File arch = sec.getSelectedFile();
       if(arch!=null){
           anuncio("",false);          
           TxtRegC.setText("");
           TxtRegG.setText("");
           TxtRegX.setText("");
           ruta=arch.getAbsolutePath();
           LeerTxt(ruta);         
       }else{
           anuncio("Ruta no especificada",true);
           bandera=1;
       }
    }//GEN-LAST:event_BtnCargar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpLoad().setVisible(true);
            }
        });
    }
    
    public void hora()
    {
        Calendar cal = new GregorianCalendar();
        Date horaactual = new Date();
        cal.setTime(horaactual);
        hora =cal.get(Calendar.HOUR_OF_DAY)>9?""+cal.get(Calendar.HOUR_OF_DAY):"0"+cal.get(Calendar.HOUR_OF_DAY) ;
        minutos=cal.get(Calendar.MINUTE)>9?""+cal.get(Calendar.MINUTE):"0"+cal.get(Calendar.MINUTE);
        segundos=cal.get(Calendar.SECOND)>9?""+cal.get(Calendar.SECOND):"0"+cal.get(Calendar.SECOND);   
    }
     public void run()
    {
        Thread current = Thread.currentThread();
        while(current == hilo)
        {
         hora();
         txtHora.setText(hora+":"+minutos+":"+segundos);
         hour=(hora+":"+minutos+":"+segundos);
        }
    }
    public String fecha()
    {
     Date fecha = new Date();
     SimpleDateFormat For = new SimpleDateFormat("dd/MM/YYYY");
             
        return For.format(fecha);
    }
    public void limpiarTabla(){
       DefaultTableModel m = new DefaultTableModel();
        m=(DefaultTableModel)TabRegA.getModel();
        while(m.getRowCount()!=0){
            m.removeRow(0);           
        }
    }
    public void LeerTxt(String dir){
        DefaultTableModel m = new DefaultTableModel();
        m=(DefaultTableModel)TabRegA.getModel();
        Date format = new Date();
        int contS=0, contN=0;
        String fila[]=new String[5];
        try{
            BufferedReader bf= new BufferedReader(new FileReader(dir));
            String aux="";
            while((aux=bf.readLine())!=null){
                contS++;
               if(noDup(aux.substring(0,6),FormatoFecha(aux.substring(6,14)),FormatoHora(aux.substring(14,20)))==true){
                   contN++;
                continue;
            }else{
              fila[0]=aux.substring(0,6);
              fila[1]=FormatoFecha(aux.substring(6,14));
              fila[2]=FormatoHora(aux.substring(14,20));
              fila[3]=aux.substring(20);
              fila[4]="";
               m.addRow(fila);               
            }
            }            
            txtException.setText("Archivo cargado");
            bandera=0;
        }catch(Exception e){
          txtException.setText("Error al cargar archivo o formato no compatible");
          bandera=1;
        // JOptionPane.showMessageDialog(null,"bbb:"+ e);
        }
        TxtRegC.setText(""+contS);           
        //contN=contN+Integer.parseInt(TxtRegX.getText());
        TxtRegX.setText(""+contN);
    }
    public boolean noDup(String C, String f, String h) throws ParseException{        
        try{            
        DefaultTableModel m = new DefaultTableModel();
         m = (DefaultTableModel) TabRegA.getModel();
         //SimpleDateFormat formI = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
         SimpleDateFormat formH = new SimpleDateFormat("hh:mm:ss");
        // SimpleDateFormat formM = new SimpleDateFormat("mm:ss");
        // SimpleDateFormat formC = new SimpleDateFormat("mm");      
         for(int i=(m.getRowCount()-1);i>=0;i--){
            if(C.equals(m.getValueAt(i,0).toString())&& f.equals(m.getValueAt(i, 1).toString())){
                Date horaT = formH.parse(m.getValueAt(i,2).toString());// obtengo la primera hora con el valor mas corto
                Date horaR = formH.parse(h); // le aplico el formato a la segunda fecha sustraida del .txt
                Calendar calT = Calendar.getInstance();  // defino la clase
                Calendar calR = Calendar.getInstance(); 
               calT.setTime(horaT);               // le asigno la var tipo date 
               calT.add(calT.MINUTE,40);          // añado 40 min para que se haga la tolerenacia de 40 min
               //int minT=cal.MINUTE;             //rescato el valor de los minutos +40
               calR.setTime(horaR);
              if(calT.compareTo(calR)>0){                                             
            //JOptionPane.showMessageDialog(null,"si funciono");
            return true;
             }else{return false;}                     
            }                  
    }     
    }catch(Exception e){
     //   JOptionPane.showMessageDialog(rootPane,"haa:"+e);
    }
            return false;
    }
    
    public void anuncio(String men, boolean mos){         
       if(mos == true){
            txtAnuncio.setText(men);            
             txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
           }
       else {
     txtAnuncio.setText("");
      txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true)); // blanco
       }       
   }
public String FormatoFecha(String fecha){
    String ano,mes,dia,fechaF;
    dia=fecha.substring(0,2);
    mes=fecha.substring(2,4);
    ano=fecha.substring(4,8);
    fechaF=ano+"-"+mes+"-"+dia;
    return fechaF;
 }
public String FormatoHora(String hora){
    String horas,min,seg,HoraF;
    horas=hora.substring(0,2);
    min=hora.substring(2,4);
    seg=hora.substring(4,6);
    HoraF=horas+":"+min+":"+seg;
    return HoraF;
}
public String fechaAct(){
     Date fecha = new Date();
     SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
     return formato.format(fecha);
 }
public void InsertD(){
     DefaultTableModel m = new DefaultTableModel();
      m=(DefaultTableModel)TabRegA.getModel();
      int ContS=0, ContN=0;
    String sql="INSERT INTO `dbregasi`.`pregasi` (`CCVEEMP`, `DFECREG`, `CNUMBIO`, `CSTATUS`, `CUSUINS`, `DFECINS`, `CUSUMOD`, `DFECMOD`) VALUES (?,?,?,?,?,?,?,?);";
       for(int i=0;i<m.getRowCount();i++){       
    try{
        PreparedStatement pst;
        pst=cn.prepareStatement(sql);          
            pst.setInt(1,Integer.parseInt(m.getValueAt(i,0).toString())); 
            pst.setString(2,(m.getValueAt(i,1).toString()+" "+m.getValueAt(i,2).toString()));
            pst.setInt(3,Integer.parseInt(m.getValueAt(i,3).toString()));        
            pst.setString(4,"A");
            pst.setString(5,"6610");
            pst.setString(6,fechaAct());
            pst.setString(7,"6610");
            pst.setString(8,fechaAct());
            m.setValueAt("Cargado",i,4);
            pst.executeUpdate();
            pst.close();
            ContS++;
    }catch(SQLException ex){
        ContN++;
        if(ex.getErrorCode()==1062){
            m.setValueAt("Duplicado",i,4);
        } else {
             m.setValueAt("Error al cargar",i,4);
        }         
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    }
       }       
       ContN=ContN+Integer.parseInt(TxtRegX.getText());
       TxtRegG.setText(""+ContS);
       TxtRegX.setText(""+ContN);
       // limpiarTabla();
}
public boolean NoIgual(int index, String clv, int col){
     DefaultTableModel m =(DefaultTableModel)TabRegA.getModel();
     index--;
     for(int i=index;i>=0;i--){       
         if(clv.equals(m.getValueAt(i,col).toString())){
            return true; 
         }
     }     
      return false;
}
public boolean Dif(int index,String clv, String f){
     DefaultTableModel m =(DefaultTableModel)TabRegA.getModel();
     index--;
     for(int i=index;i>=0;i--){         
         if(clv.equals(m.getValueAt(i,0).toString())&& f.equals(m.getValueAt(i,1).toString())){
             return true;                        
         }
     }     
      return false;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnCargar1;
    private javax.swing.JTable TabRegA;
    private javax.swing.JTextField TxtRegC;
    private javax.swing.JTextField TxtRegG;
    private javax.swing.JTextField TxtRegX;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAnuncio;
    private javax.swing.JTextField txtException;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
