/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sasistencia;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author final
 */
public class Usuario extends javax.swing.JFrame {
Conectar cc=new Conectar();
Connection cn= cc.conexion();
UsuarioActivo user = new UsuarioActivo();
private int clv=0;
    /**
     * Creates new form JFUsuario
     */
//String acces="Admin";
    public Usuario() {
        initComponents();
        Estad();
        Preparar();
        txtCvee.setEditable(false);       
        SPNom.setVisible(false);
        txtFe.setEditable(false);
        txtCvee.setEditable(false);
        txtClavH.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupTipoU = new javax.swing.ButtonGroup();
        jPanel11 = new javax.swing.JPanel();
        TabPanEmp = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JPInfo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        txtNumext = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtNumint = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        cmbMun = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtCp = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        txtMun = new javax.swing.JTextField();
        PnTipU = new javax.swing.JPanel();
        rdbAdmin = new javax.swing.JRadioButton();
        rdbOtro = new javax.swing.JRadioButton();
        txtConfirmar = new javax.swing.JPasswordField();
        txtContra = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtAnuncio = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        SPNom = new javax.swing.JScrollPane();
        TabNom = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCu = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtFe = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cmbEstad = new javax.swing.JComboBox<>();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        txtCvee = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jPanel17 = new javax.swing.JPanel();
        txtCall = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        cmbEsta = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        cmbMuni = new javax.swing.JComboBox<>();
        txtCol = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        txtInt = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        txtExt = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        txtNomU = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jPanel21 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Tab = new javax.swing.JTable();
        txtClavH = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtClaveEmp = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabPanEmp.setBackground(new java.awt.Color(255, 255, 255));
        TabPanEmp.setForeground(new java.awt.Color(19, 141, 117));
        TabPanEmp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPInfo.setBackground(new java.awt.Color(255, 255, 255));
        JPInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 141, 117)));
        JPInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 141, 117));
        jLabel7.setText("Calle *");
        JPInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(19, 141, 117));
        jLabel8.setText("num ext*");
        JPInfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(19, 141, 117));
        jLabel9.setText("Estado de la republica");
        JPInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(19, 141, 117));
        jLabel10.setText("num int");
        JPInfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(19, 141, 117));
        jLabel11.setText("Colonia *");
        JPInfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        txtCalle.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCalle.setBorder(null);
        JPInfo.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 190, 24));

        txtNumext.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtNumext.setBorder(null);
        txtNumext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumextKeyTyped(evt);
            }
        });
        JPInfo.add(txtNumext, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 190, 24));

        txtColonia.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtColonia.setBorder(null);
        JPInfo.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 190, 24));

        txtNumint.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtNumint.setBorder(null);
        txtNumint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumintKeyTyped(evt);
            }
        });
        JPInfo.add(txtNumint, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 190, 24));

        jLabel6.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(19, 141, 117));
        jLabel6.setText("Segundo Apellido*");
        JPInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 141, 117));
        jLabel3.setText("Primer Apellido*");
        JPInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 141, 117));
        jLabel2.setText("Nombres *");
        JPInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txtNombres.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        JPInfo.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, 24));

        txtApellido1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtApellido1.setBorder(null);
        txtApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido1KeyTyped(evt);
            }
        });
        JPInfo.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 24));

        txtApellido2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtApellido2.setBorder(null);
        JPInfo.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, 24));

        jLabel12.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(19, 141, 117));
        jLabel12.setText("Tipo de Usuario*");
        JPInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(19, 141, 117));
        jLabel5.setText("Fecha de ingreso*");
        JPInfo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 141, 117));
        jLabel4.setText("Curp*");
        JPInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 50, -1));

        txtCurp.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCurp.setBorder(null);
        txtCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurpKeyTyped(evt);
            }
        });
        JPInfo.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 190, 24));

        txtFecha.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtFecha.setBorder(null);
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });
        JPInfo.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 190, 24));

        txtUsuario.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);
        JPInfo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 182, 24));

        jLabel13.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(19, 141, 117));
        jLabel13.setText("Nombre de Usuario*");
        JPInfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(19, 141, 117));
        jLabel14.setText("Contraseña*");
        JPInfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        jLabel15.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(19, 141, 117));
        jLabel15.setText("Confirme Contraseña*");
        JPInfo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));
        JPInfo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 180, 10));
        JPInfo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 180, 10));
        JPInfo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 190, 10));
        JPInfo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, 10));
        JPInfo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 190, 10));
        JPInfo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 190, 10));
        JPInfo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 180, 10));
        JPInfo.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 190, 10));
        JPInfo.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 190, 10));
        JPInfo.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 296, 190, 10));
        JPInfo.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 180, 10));
        JPInfo.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 180, 10));

        jPanel3.setBackground(new java.awt.Color(19, 141, 117));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(255, 0, 0));
        jLabel24.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Informacion del Empleado");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        JPInfo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 40));

        jPanel7.setBackground(new java.awt.Color(19, 141, 117));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Dirección");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        JPInfo.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, 40));

        jPanel8.setBackground(new java.awt.Color(19, 141, 117));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Asignacion de Usuario");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        JPInfo.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 310, 40));

        jLabel17.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(19, 141, 117));
        jLabel17.setText("Correo*");
        JPInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCorreo.setBorder(null);
        JPInfo.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 180, 24));
        JPInfo.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 180, 10));

        jLabel19.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(19, 141, 117));
        jLabel19.setText("Alcaldia / municipio*");
        JPInfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        cmbMun.setBackground(new java.awt.Color(255, 255, 255));
        cmbMun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        JPInfo.add(cmbMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 200, -1));

        cmbEstado.setBackground(new java.awt.Color(255, 255, 255));
        cmbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        cmbEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbEstadoMouseClicked(evt);
            }
        });
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        JPInfo.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, -1));

        jLabel20.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(19, 141, 117));
        jLabel20.setText("Codigo Postal*");
        JPInfo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        txtCp.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCp.setBorder(null);
        txtCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpActionPerformed(evt);
            }
        });
        txtCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpKeyTyped(evt);
            }
        });
        JPInfo.add(txtCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 190, 24));
        JPInfo.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 190, 10));

        txtMun.setBackground(new java.awt.Color(255, 255, 255));
        txtMun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMun.setForeground(new java.awt.Color(0, 0, 0));
        txtMun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        txtMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunActionPerformed(evt);
            }
        });
        JPInfo.add(txtMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 160, -1));

        PnTipU.setBackground(new java.awt.Color(255, 255, 255));
        PnTipU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        PnTipU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdbAdmin.setBackground(new java.awt.Color(255, 255, 255));
        grupTipoU.add(rdbAdmin);
        rdbAdmin.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rdbAdmin.setForeground(new java.awt.Color(19, 141, 117));
        rdbAdmin.setText("Administrativo");
        rdbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAdminActionPerformed(evt);
            }
        });
        PnTipU.add(rdbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        rdbOtro.setBackground(new java.awt.Color(255, 255, 255));
        grupTipoU.add(rdbOtro);
        rdbOtro.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rdbOtro.setForeground(new java.awt.Color(19, 141, 117));
        rdbOtro.setText("Otro");
        rdbOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOtroActionPerformed(evt);
            }
        });
        PnTipU.add(rdbOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        JPInfo.add(PnTipU, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 240, 50));

        txtConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtConfirmar.setBorder(null);
        JPInfo.add(txtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 180, 26));

        txtContra.setBackground(new java.awt.Color(255, 255, 255));
        txtContra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContra.setBorder(null);
        JPInfo.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 482, 180, 26));

        jLabel23.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(19, 141, 117));
        jLabel23.setText("Desactivado");
        JPInfo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 160, -1));

        jLabel46.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(19, 141, 117));
        jLabel46.setText("Estado del usuario*");
        JPInfo.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 160, -1));

        jPanel1.add(JPInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 600));

        jPanel4.setBackground(new java.awt.Color(19, 141, 117));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 141, 117));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 270, 60));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Nuevo");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 270, 60));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Regresar");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 270, 60));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 285, 270));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 320, 330));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 141, 117)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(19, 141, 117));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnuncio.setBackground(new java.awt.Color(19, 141, 117));
        txtAnuncio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAnuncio.setForeground(new java.awt.Color(255, 255, 255));
        txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel6.add(txtAnuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 320, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 320, 260));

        jPanel9.setBackground(new java.awt.Color(19, 141, 117));
        jPanel9.setForeground(new java.awt.Color(19, 141, 117));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Opciones");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 130, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 270, 40));

        jPanel10.setBackground(new java.awt.Color(19, 141, 117));
        jPanel10.setForeground(new java.awt.Color(19, 141, 117));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Registro De Empleado");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, 40));

        TabPanEmp.addTab("Registro de Empleado", jPanel1);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SPNom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));

        TabNom.setBackground(new java.awt.Color(255, 255, 255));
        TabNom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TabNom.setForeground(new java.awt.Color(102, 102, 102));
        TabNom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabNom.setEditingColumn(0);
        TabNom.setGridColor(new java.awt.Color(255, 255, 255));
        TabNom.setRowHeight(18);
        TabNom.setRowMargin(2);
        TabNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabNomMouseClicked(evt);
            }
        });
        SPNom.setViewportView(TabNom);

        jPanel12.add(SPNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 360, 50));

        jPanel14.setBackground(new java.awt.Color(19, 141, 117));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 0, 0));
        jLabel25.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Consultar empleado por");
        jPanel14.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 30));

        PanelInfo.setBackground(new java.awt.Color(255, 255, 255));
        PanelInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        PanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(19, 141, 117));
        jLabel21.setText("Nombres ");
        PanelInfo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        txtNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        PanelInfo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, 24));

        jLabel22.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(19, 141, 117));
        jLabel22.setText("Apellidos");
        PanelInfo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtApellidos.setBorder(null);
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        PanelInfo.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, 24));

        jLabel27.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(19, 141, 117));
        jLabel27.setText("Curp");
        PanelInfo.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 50, -1));

        txtCu.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCu.setBorder(null);
        txtCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuKeyTyped(evt);
            }
        });
        PanelInfo.add(txtCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 190, 24));

        jLabel29.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(19, 141, 117));
        jLabel29.setText("Fecha de ingreso");
        PanelInfo.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        txtFe.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtFe.setBorder(null);
        txtFe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFeKeyTyped(evt);
            }
        });
        PanelInfo.add(txtFe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 190, 24));

        jLabel30.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(19, 141, 117));
        jLabel30.setText("Estado del usuario");
        PanelInfo.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        cmbEstad.setBackground(new java.awt.Color(255, 255, 255));
        cmbEstad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        cmbEstad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbEstadMousePressed(evt);
            }
        });
        cmbEstad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadActionPerformed(evt);
            }
        });
        PanelInfo.add(cmbEstad, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 180, -1));
        PanelInfo.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 190, 10));
        PanelInfo.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 180, 10));
        PanelInfo.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 190, 10));
        PanelInfo.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, 10));

        jLabel45.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(19, 141, 117));
        jLabel45.setText("Clave de Empleado:");
        PanelInfo.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 170, -1));

        txtCvee.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCvee.setBorder(null);
        txtCvee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCveeKeyTyped(evt);
            }
        });
        PanelInfo.add(txtCvee, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 60, 190, 24));
        PanelInfo.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 87, 190, 10));

        jPanel12.add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1150, 120));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCall.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCall.setBorder(null);
        jPanel17.add(txtCall, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 190, 24));

        jLabel35.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(19, 141, 117));
        jLabel35.setText("Calle ");
        jPanel17.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));
        jPanel17.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 190, 10));

        jLabel36.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(19, 141, 117));
        jLabel36.setText("Estado de la republica");
        jPanel17.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cmbEsta.setBackground(new java.awt.Color(255, 255, 255));
        cmbEsta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel17.add(cmbEsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, 250, -1));

        jLabel37.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(19, 141, 117));
        jLabel37.setText("Delegacion / municipio*");
        jPanel17.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, -1, -1));

        cmbMuni.setBackground(new java.awt.Color(255, 255, 255));
        cmbMuni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel17.add(cmbMuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, 250, -1));

        txtCol.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCol.setBorder(null);
        jPanel17.add(txtCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 190, 24));

        jLabel38.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(19, 141, 117));
        jLabel38.setText("Colonia ");
        jPanel17.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));
        jPanel17.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 190, 10));

        jLabel39.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(19, 141, 117));
        jLabel39.setText("num int");
        jPanel17.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        txtInt.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtInt.setBorder(null);
        txtInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIntKeyTyped(evt);
            }
        });
        jPanel17.add(txtInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 90, 24));
        jPanel17.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, 10));

        jLabel40.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(19, 141, 117));
        jLabel40.setText("num ext");
        jPanel17.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txtExt.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtExt.setBorder(null);
        txtExt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExtKeyTyped(evt);
            }
        });
        jPanel17.add(txtExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 90, 24));
        jPanel17.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 10));

        jLabel41.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(19, 141, 117));
        jLabel41.setText("Codigo Postal");
        jPanel17.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        txtCod.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtCod.setBorder(null);
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodKeyTyped(evt);
            }
        });
        jPanel17.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 120, 24));
        jPanel17.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 120, 10));

        jPanel12.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1150, 130));

        jPanel15.setBackground(new java.awt.Color(19, 141, 117));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(255, 0, 0));
        jLabel32.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Credenciales de empleado");
        jPanel15.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 290, 30));

        jPanel19.setBackground(new java.awt.Color(19, 141, 117));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(255, 0, 0));
        jLabel34.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Informacion del Empleado");
        jPanel19.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel12.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 30));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(19, 141, 117));
        jLabel43.setText("Nombre de Usuario");
        jPanel20.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtNomU.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtNomU.setBorder(null);
        jPanel20.add(txtNomU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 182, -1));
        jPanel20.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 180, 10));

        jLabel44.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(19, 141, 117));
        jLabel44.setText("Correo electronico");
        jPanel20.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtMail.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        txtMail.setBorder(null);
        jPanel20.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 180, -1));
        jPanel20.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 180, 10));

        jPanel12.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 400, 130));

        jPanel21.setBackground(new java.awt.Color(19, 141, 117));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setBackground(new java.awt.Color(255, 0, 0));
        jLabel42.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Dirección de empleado");
        jPanel21.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel12.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 310, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Regresar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, 150, 50));

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel49.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 1, true));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel50.setBackground(new java.awt.Color(19, 141, 117));
        jPanel50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Martes");
        jPanel50.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel51.setBackground(new java.awt.Color(19, 141, 117));
        jPanel51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Lunes");
        jPanel51.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel50.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 10, 132, 40));

        jPanel49.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 132, 30));

        jPanel52.setBackground(new java.awt.Color(19, 141, 117));
        jPanel52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Miercoles");
        jPanel52.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, 30));

        jPanel53.setBackground(new java.awt.Color(19, 141, 117));
        jPanel53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Lunes");
        jPanel53.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel52.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 10, 132, 40));

        jPanel49.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 132, 30));

        jPanel54.setBackground(new java.awt.Color(19, 141, 117));
        jPanel54.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Jueves");
        jPanel54.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel55.setBackground(new java.awt.Color(19, 141, 117));
        jPanel55.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Lunes");
        jPanel55.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel54.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 10, 132, 40));

        jPanel49.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 132, 30));

        jPanel56.setBackground(new java.awt.Color(19, 141, 117));
        jPanel56.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Viernes");
        jPanel56.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel57.setBackground(new java.awt.Color(19, 141, 117));
        jPanel57.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Lunes");
        jPanel57.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel56.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 10, 132, 40));

        jPanel49.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 132, 30));

        jPanel58.setBackground(new java.awt.Color(19, 141, 117));
        jPanel58.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel58.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Lunes");
        jPanel58.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel49.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 132, 30));

        jPanel12.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 530, 736, 40));

        Tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entrada", "Salida", "Entrada", "Salida", "Entrada", "Salida", "Entrada", "Salida", "Entrada", "Salida"
            }
        ));
        jScrollPane9.setViewportView(Tab);

        jPanel12.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 740, 60));

        txtClavH.setBackground(new java.awt.Color(255, 255, 255));
        txtClavH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtClavH.setForeground(new java.awt.Color(0, 0, 0));
        txtClavH.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true), "Clav de horario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel12.add(txtClavH, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 180, 50));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btnSave.setForeground(new java.awt.Color(102, 102, 102));
        btnSave.setText("Guardar");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 3, true));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel12.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 530, 150, 50));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Clave de empleado");
        jPanel12.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtClaveEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtClaveEmp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClaveEmp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        jPanel12.add(txtClaveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Nombre de empleado");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 2, true));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel12.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 360, 30));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 102, 102));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 141, 117), 3, true));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel12.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, 50));

        TabPanEmp.addTab("Consultar", jPanel12);

        jPanel11.add(TabPanEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 700));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumextKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtNumextKeyTyped

    private void txtNumintKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumintKeyTyped
 //       char c= evt.getKeyChar();
   //     if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtNumintKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped

        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')
            && car !='á' //Minúsculas
            && car !='é'
            && car !='í'
            && car !='ó'
            && car !='ú'
            && car !='Á' //Mayúsculas
            && car !='É'
            && car !='Í'
            && car !='Ó'
            && car !='Ú'
            && car !='ñ'
            && car !='Ñ'
            && (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();

        }
        
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1KeyTyped

        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')
            && car !='á' //Minúsculas
            && car !='é'
            && car !='í'
            && car !='ó'
            && car !='ú'
            && car !='Á' //Mayúsculas
            && car !='É'
            && car !='Í'
            && car !='Ó'
            && car !='Ú'
            && car !='ñ'
            && car !='Ñ'
            && (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();

        }
    }//GEN-LAST:event_txtApellido1KeyTyped

    private void txtCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpKeyTyped
      /*  char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();*/

    }//GEN-LAST:event_txtCurpKeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtFechaKeyTyped

    private void rdbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAdminActionPerformed
     
    }//GEN-LAST:event_rdbAdminActionPerformed

    private void rdbOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOtroActionPerformed
        
    }//GEN-LAST:event_rdbOtroActionPerformed

    private void txtCpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtCuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuKeyTyped

    private void txtFeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeKeyTyped

    private void txtIntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntKeyTyped

    private void txtExtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExtKeyTyped

    private void txtCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(NoVacio()==true){
            anuncio("Por favor llene las casillas marcadas",true);           
        }else{
             anuncio("",false);
             if(puesto().equals("Error")){
                 anuncio("Por favor llena los recuadros marcados",true);
             }
             else{
                 if(np()==false){
                   if(insertEmp()==false){
                       InsertCred();
                       anuncio("Usuario Registrado, Clave asignada: "+clv,true);
                       clr();
                   }
                 }
             }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunActionPerformed

    private void txtCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clr();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cmbEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEstadoMouseClicked
       
    }//GEN-LAST:event_cmbEstadoMouseClicked

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
          if(cmbEstado.getSelectedIndex()==8){
        cmbMun.setEnabled(true);
    }
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

   if(txtClaveEmp.getText().length()!=0){
       anuncio("",false);
        txtClaveEmp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19,141,117), 2, true)); // verde
        String ccve=txtClaveEmp.getText();
   String sql="SELECT * FROM `ddatemp` WHERE ccveemp ="+ccve+";";
    llenar(sql);
    sql="SELECT usuario, correo  FROM credenciales WHERE credenciales.ccveemp ="+ccve;
   // JOptionPane.showMessageDialog(null,sql);
    consulU(sql);  
    consultHor();
   }else{
       txtClaveEmp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
       anuncio("LLene los recuadros marcados",true);       
   }     
  
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCveeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCveeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCveeKeyTyped

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      if(txtBuscar.getText().equals("")){
      SPNom.setVisible(false);   
      }
      else{
       SPNom.setVisible(true);     
        String [] t = {"","",""};
        String nom="",ap="";
      /*  StringTokenizer StT = new StringTokenizer(txtBuscar.getText()," ");
        while(StT.hasMoreElements()){
            nom=StT.nextToken();
            ap=StT.nextToken();
        }*/       
        DefaultTableModel m = new DefaultTableModel(null,t);      
         ResultSet rs;
        Statement st;
        String [] nombre = new String [3];
        try{
        String sql="SELECT CNOMBRE, CAPEUNO, CAPEDOS FROM ddatemp WHERE CNOMBRE like '%"+txtBuscar.getText()+"%'";
        //JOptionPane.showMessageDialog(null,sql);
        st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next())
        {
            nombre[0]=rs.getString(1);
            nombre[1]=rs.getString(2);
            nombre[2]=rs.getString(3);
            m.addRow(nombre);
        }       
        TabNom.setEditingRow(-1);
        TabNom.setModel(m);      
        rs.close();
          int x = m.getRowCount();
        int y = 20+x*18;
        SPNom.setSize(360,y);
        int height = SPNom.getSize().height;
         if(height>=140){
        SPNom.setSize(360,140);
      }
        }catch(SQLException ex){
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
        }
      }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void TabNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabNomMouseClicked
      DefaultTableModel m = new DefaultTableModel();
      m=(DefaultTableModel) TabNom.getModel();
      int row =m.getRowCount();      
      	int height = SPNom.getSize().height;
         int y = 20+row*18;
      SPNom.setSize(360,y );
      if(height>=140){
     SPNom.setSize(360,140);    
      }
       SPNom.setVisible(false);
       if(TabNom.getSelectedRow()!=-1){
       String Nombre,Ap1,Ap2;
       Nombre=String.valueOf(m.getValueAt(TabNom.getSelectedRow(),0));
       Ap1=String.valueOf(m.getValueAt(TabNom.getSelectedRow(),1));
       Ap2=String.valueOf(m.getValueAt(TabNom.getSelectedRow(),2));
        String sql ="SELECT * FROM ddatemp WHERE CNOMBRE ='"+Nombre+"' and CAPEUNO = '"+Ap1+"'AND CAPEDOS ='"+Ap2+"'";
        llenar(sql);
        sql="SELECT usuario, correo  FROM credenciales WHERE credenciales.ccveemp = (SELECT ccveemp from ddatemp WHERE CNOMBRE ='"+Nombre+"' and CAPEUNO = '"+Ap1+"'AND CAPEDOS ='"+Ap2+"')";
        consulU(sql);
       consultHor();}
       else{JOptionPane.showMessageDialog(null, "Elija un elemento de la tabla");}
    }//GEN-LAST:event_TabNomMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(noVacioC()==0){           
            String[] parts = txtApellidos.getText().split(" ");
            String Ap1 = parts[0]; // 004
            String Ap2 = parts[1]; // 034556
            String estad="";
            if(cmbEstad.getSelectedIndex()==0){                
                estad="A";                   
            }
            else{estad="D";}            
            String sql="UPDATE ddatemp SET CNOMBRE='"+txtNombre.getText()+"', CAPEUNO='"+Ap1+"',CAPEDOS='"+Ap2+"', CCURPEM='"+txtCu.getText()+"', CNMCALL='"+txtCall.getText()+"', CNUMEXT='"+txtExt.getText()+
                    "', CNUMINT='"+txtInt.getText()+"', CCOLONI='"+txtCol.getText()+"', CCODPOS='"+txtCod.getText()+"', NIDESTA='"+(cmbEsta.getSelectedIndex()+1)+"', NIDMUNI='"+(cmbMuni.getSelectedIndex()+1)+"', CSTATUS='"+estad+"', CUSUMOD='"+user.getClvUser()+"', DFECMOD='"+fecha()+"' WHERE CCVEEMP = '"+txtCvee.getText()+"';"; 
            update(sql);
            sql="UPDATE credenciales SET `Usuario` = '"+txtNomU.getText()+"', `Correo` = '"+txtMail.getText()+"' WHERE ccveemp ='"+txtCvee.getText()+"' ;";
            update(sql);
            clrC();
            JOptionPane.showMessageDialog(null,"Datos Actualizados");
        }
        else{
            JOptionPane.showMessageDialog(null,"Por favor llene los recuadros marcados");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(user.getModoAcceso().equals("Admin")){
            TabPanEmp.setEnabledAt(0,true);
            txtBuscar.setEnabled(true);
            txtClaveEmp.setEnabled(true);
        }
        else{
            TabPanEmp.setSelectedIndex(1);
            TabPanEmp.setEnabledAt(0,false);
        txtBuscar.setEnabled(false);
            txtClaveEmp.setEnabled(false);
            String sql="SELECT * FROM `ddatemp` WHERE ccveemp ="+user.getClvEmp()+";";
    llenar(sql);
            
    sql="SELECT usuario, correo  FROM credenciales WHERE credenciales.ccveemp ="+user.getClvEmp();
   // JOptionPane.showMessageDialog(null,sql);
    consulU(sql);  
    consultHor();
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmbEstadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEstadMousePressed
      
    }//GEN-LAST:event_cmbEstadMousePressed

    private void cmbEstadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadActionPerformed
         
        if(txtCvee.getText().length()!=0){
        if(cmbEstad.getSelectedIndex()==0){
                String sql="SELECT CSTATUS FROM `ddatemp` where ccveemp = '"+txtCvee.getText()+"'";
                String estado="";
               Statement st;
                ResultSet rs;
                try{                     
                    st=(Statement) cn.createStatement();
                    rs=st.executeQuery(sql);
                   while(rs.next()){           
                    estado=rs.getString(1);
                   }        
                    rs.close();                                    
                }catch(SQLException ex){
                     Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
                }   
                if(estado.equals("A")){
                    cmbEstad.setSelectedIndex(0);
                }else{                   
                    JOptionPane.showMessageDialog(null,"Solo se puede activar un usuario asignandole un horario");
                       cmbEstad.setSelectedIndex(1);
                }                
            }         
        }
    }//GEN-LAST:event_cmbEstadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }
    public void llenar(String sql){    
        String es;
        int estad,muni;
    if(verificar(sql)==true){
    ResultSet rs;            
    Statement st;       
    try{       
        st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){      
        txtCvee.setText(rs.getString(1));
        txtNombre.setText(rs.getString(2));
        txtApellidos.setText(rs.getString(3)+" "+rs.getString(4));
        txtCu.setText(rs.getString(5));
        txtFe.setText(rs.getString(6));
        txtCall.setText(rs.getString(7));
        txtExt.setText(rs.getString(8));
        txtInt.setText(rs.getString(9));
        txtCol.setText(rs.getString(10));
        txtCod.setText(rs.getString(11));
        estad=rs.getInt(12)-1;
        cmbEsta.setSelectedIndex(estad);
        muni=rs.getInt(13)-1;
        cmbMuni.setSelectedIndex(muni);
         es=rs.getString(14);
        if(es.equals("A")){
            cmbEstad.setSelectedIndex(0);
        }
        else{cmbEstad.setSelectedIndex(1);}
        }       
        rs.close();       
    }
    catch(SQLException ex){        
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    } 
    }
    else{
         JOptionPane.showMessageDialog(null,"Datos de usuario no encontrados");
    clrC();}
    }
    
    public boolean insertEmp(){
       char e;       
       String sql="INSERT INTO `dbregasi`.`ddatemp` (`CCVEEMP`, `CNOMBRE`, `CAPEUNO`, `CAPEDOS`, `CCURPEM`, `DFECING`, `CNMCALL`, `CNUMEXT`, `CNUMINT`, `CCOLONI`, `CCODPOS`, `NIDESTA`, `NIDMUNI`, `CSTATUS`, `CUSUINS`, `DFECINS`, `CUSUMOD`, `DFECMOD`) "+
              " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?);";        
       try{
       PreparedStatement pst;
        pst=cn.prepareStatement(sql);
        clv=genClav("CCVEEMP","ddatemp");
        txtAnuncio.setText(""+clv);
        if(clv==0){ 
            anuncio("Error al asiganar clave",true);
            return true;
        }
        else{   
        anuncio("",false);
        pst.setInt(1,clv);
        pst.setString(2,txtNombres.getText());
        pst.setString(3,txtApellido1.getText());
        pst.setString(4,txtApellido2.getText());
        pst.setString(5,txtCurp.getText());
        pst.setString(6,fecha());
        pst.setString(7,txtCalle.getText());
        pst.setInt(8,Integer.parseInt(txtNumext.getText()));
       pst.setString(9,txtNumint.getText());
        pst.setString(10, txtColonia.getText());
        pst.setInt(11,Integer.parseInt(txtCp.getText()));
        pst.setInt(12,(cmbEstado.getSelectedIndex()+1));/////////////////////////////////checar        
        pst.setInt(13,(cmbMun.getSelectedIndex()+1));               
        pst.setString(14,"D");
        pst.setInt(15,user.getClvUser());
        pst.setString(16,fecha());
        pst.setInt(17,user.getClvUser());
        pst.setString(18,fecha());
        pst.executeUpdate();
        pst.close();
        return false;
        }
       }catch(SQLException ex){
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
        //anuncio("Error",true);
    } 
       return true;
    }    
    public void InsertCred(){
        String sql="INSERT INTO `dbregasi`.`credenciales` (`id_Credenciales`, `CCVEEMP`, `Usuario`, `Pass`, `Correo`, `ModAces`) VALUES (?, ?, ? , ?, ?, ?);";      
        try{     
             PreparedStatement pst;
        pst=cn.prepareStatement(sql);
        int clav=genClav("id_Credenciales","credenciales");
        if(clav==0){ 
             anuncio("Error al asiganar clave de usuario",true);
        }
        else{
             anuncio("",false);
            pst.setInt(1,clav);
            pst.setInt(2, clv);
            pst.setString(3, txtUsuario.getText());
            pst.setString(4,txtConfirmar.getText());
            pst.setString(5,txtCorreo.getText());
            pst.setString(6,puesto());
            pst.executeUpdate();
            pst.close();
        }
        }catch(SQLException ex){
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
          anuncio("Error",true);
    }
    }    
 public String puesto(){
     if(rdbAdmin.isSelected()){        
         txtAnuncio.setText("");            
             txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 2, true)); // rojo
             PnTipU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19,141,117), 1, true)); // verde
              return "Admin";
     }
     else{
     if(rdbOtro.isSelected()){
         txtAnuncio.setText("");            
             txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 2, true)); // rojo
             PnTipU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19,141,117), 1, true)); // verde
         return "NAdmin";
     }
     else{                  
             txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
             PnTipU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 1, true));
         return "Error";         
     }    }
 }    
 public void Estad(){     
       ResultSet rs;
    Statement st;  
    String sql="SELECT cnomest FROM `cestads` ORDER BY `NIDESTA` ASC";
    String estado,municip;
    try{
         st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){
            estado=rs.getString(1);
        cmbEstado.addItem(estado);        
        cmbEsta.addItem(estado);
        }
        sql="SELECT cnommun FROM `cmunics` ORDER BY `cmunics`.`NIDMUNI` ASC";
        rs=st.executeQuery(sql);
        while(rs.next()){
            municip=rs.getString(1);
            cmbMun.addItem(municip);
            cmbMuni.addItem(municip);
        }
        rs.close();
        st.close();
    }catch(SQLException ex){
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    }
 }
public int genClav(String campid, String camptab){
    int ClvEmp=0;
    String sql ="SELECT "+campid+" FROM "+camptab+" ORDER BY "+campid+" DESC limit 1";
  //  txtAnuncio.setText(sql);
    Statement st ;
    ResultSet rs;
    try{
         //txtAnuncio.setText(sql+" //"+ClvEmp);
        st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
       while(rs.next()){           
        ClvEmp=rs.getInt(1);
       }        
        rs.close();
        ClvEmp++;
       
         return ClvEmp;
    }catch(SQLException ex){
         Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    }   
    return ClvEmp;
}
/*public int noClvEmp(String a, String b){
    int ClvEmp= genClav(a,b);
    if(ClvEmp==0){
        return 0;
    }
    else
    {
         anuncio("",false);
          return ClvEmp; 
    }
   
}*/
 public String fecha(){
     Date fecha = new Date();
     SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
     return formato.format(fecha);
 }
 public void Preparar(){
     txtFecha.setEditable(false);
     Date fecha = new Date();
     SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
     txtFecha.setText(formato.format(fecha));
     String [] estado ={"Activo","Desactivado"};
     DefaultComboBoxModel c = new DefaultComboBoxModel(estado);     
     cmbMun.setEditable(false);
     cmbEstad.setModel(c);
 }
public void anuncio(String men, boolean mos){         
       if(mos == true){
            txtAnuncio.setText(men);            
             txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
           }
       else {
     txtAnuncio.setText("");
      txtAnuncio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true)); // blanco
       }       
   }
public boolean NoVacio(){
    int bandera=0;
    if(vacio(txtNombres)==true){ bandera=1; }    
    if(vacio(txtApellido1)==true){ bandera=1; }
    if(vacio(txtApellido2)==true){ bandera=1; }
    if(vacio(txtCurp)==true){ bandera=1; }
    if(vacio(txtCalle)==true){ bandera=1; }
    if(vacio(txtColonia)==true){ bandera=1; }
    if(vacio(txtNumext)==true){ bandera=1; }
    if(vacio(txtCp)==true){ bandera=1; }
    if(vacio(txtUsuario)==true){ bandera=1; }
    if(vacio(txtContra)==true){ bandera=1; }
    if(vacio(txtConfirmar)==true){ bandera=1; }
    if(vacio(txtCorreo)==true){ bandera=1; }   
    if(cmbEstado.getSelectedIndex()!=8){
     if(vacio(txtMun)==true){ bandera=1; }
    }
    
    if(bandera==0){
        return false;
    }
    else
      return true;
}
public boolean vacio(JTextField txt){
    if(txt.getText().equals("")){
       txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
        return true;
    }else{
        txt.setBorder(null);
        return false;
    }    
}

public boolean noUser(){
    ResultSet rs;            
    Statement st;
    String result="";
 String sql="SELECT usuario FROM `credenciales` WHERE  usuario='"+txtUsuario.getText()+"'";  
    try{       
        st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){
        rs.last();
        result=rs.getString(1);
        }               
        rs.close();
        if(result==null){           
            result="";
        }
        if(result.equals("")){
            return false;
        }
        else{
            return true;}
    }
    catch(SQLException ex){        
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    }
    return true;
}
public boolean np(){
    String men=txtAnuncio.getText();
    if(noUser()==true){
        men=txtAnuncio.getText();
        anuncio("Usuario ya registrado",true);
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
        return true;
    }
    else{
        anuncio("",false);
        txtUsuario.setBorder(null);
    
    if(txtContra.getText().equals(txtConfirmar.getText())){
       anuncio("",false);
        txtContra.setBorder(null);
        txtConfirmar.setBorder(null);
        return false;
    }
    else{
          txtContra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
          txtConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204,0,0), 2, true)); // rojo
        anuncio("La Contraseña no coincide",true); 
        return true;
    }
    }
}
public void clr(){
    txtNombres.setText("");
    txtApellido1.setText("");
    txtApellido2.setText("");
    txtCurp.setText("");
    txtCalle.setText("");
    txtColonia.setText("");
    txtNumint.setText("");
    txtNumext.setText("");
    txtCp.setText("");
    txtCorreo.setText("");
    txtUsuario.setText("");
    txtContra.setText("");
    txtConfirmar.setText("");
    rdbAdmin.setSelected(false);
    rdbOtro.setSelected(false);
}
public boolean verificar(String sql){
    ResultSet rs;            
    Statement st;
    String result=""; 
    try{       
        st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){      
        result=rs.getString(1);
        }               
        rs.close();
        if(result==null){           
            result="";            
        }
        if(result.equals("")){
           
            return false;
            
        }
        else{
        return true;
        }           
    }
    catch(SQLException ex){        
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    }
    return false;
}
public void consulU(String sql){    
    boolean v= verificar(sql);
    if(v==true){
    ResultSet rs;            
    Statement st;  
    try{       
        st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){      
       txtNomU.setText(rs.getString(1));
       txtMail.setText(rs.getString(2));
        }
    }catch(SQLException ex){        
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    }
    }
    else{
    JOptionPane.showMessageDialog(null,"Credenciales de usuario no encontradas");
    clrC();
    }
}
public void clrC(){
    txtClaveEmp.setText("");
    txtBuscar.setText("");
    txtNomU.setText("");
    txtMail.setText("");
    txtNombre.setText("");
    txtApellidos.setText("");
    txtCu.setText("");
    txtFe.setText("");
    txtCvee.setText("");
    txtExt.setText("");
    txtInt.setText("");
    txtCall.setText("");
    txtCol.setText("");
    txtCod.setText("");
}
public void update(String sql){   
   try{
    PreparedStatement pst = cn.prepareStatement(sql);
    pst.executeUpdate();    
    }catch(SQLException ex){
       Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex); 
    }
}
public int noVacioC(){
    int bandera=0;    
    if(vacio(txtCvee)){bandera =1;}
    if(vacio(txtNombre)){bandera =1;}
    if(vacio(txtApellidos)){bandera =1;}
    if(vacio(txtCu)){bandera =1;}
    if(vacio(txtExt)){bandera =1;}
    if(vacio(txtInt)){bandera =1;}
    if(vacio(txtCall)){bandera =1;}
    if(vacio(txtCol)){bandera =1;}
    if(vacio(txtCod)){bandera =1;}
    if(vacio(txtNomU)){bandera =1;}
    if(vacio(txtMail)){bandera =1;}   
    return bandera;
}
public void consultHor(){
    DefaultTableModel modelo = new DefaultTableModel();    
    modelo =(DefaultTableModel) Tab.getModel();
     txtClavH.setText("");
    while(modelo.getRowCount()>0){
        modelo.removeRow(0);
    }
    //int clvEmp=Integer.parseInt(txtCvee.getText());    
    String sql ="select nidhora,chorent,chorsal from ddethor where nidhora in (select nidhora from dhremps where ccveemp ='"+txtCvee.getText()+"')";
  //  JOptionPane.showMessageDialog(null,sql);
    String[] fila = new String [10];
     ResultSet rs;            
    Statement st;   
    String rep;
    int i=0;
    try{       
        st=(Statement) cn.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){
            rep=rs.getString(1);
         if(rep==null){
           JOptionPane.showMessageDialog(null,"Usuario sin horario ");
           break;
         }   
         else                   
        fila[i*2]=rs.getString(2);
        fila[i*2+1]=rs.getString(3);
        txtClavH.setText(rs.getString(1));
        i++;
        } 
        modelo.addRow(fila);      
        rs.close();
        st.close();
    }
    catch(SQLException ex){        
        Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE,null,ex);
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPInfo;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PnTipU;
    private javax.swing.JScrollPane SPNom;
    private javax.swing.JTable Tab;
    private javax.swing.JTable TabNom;
    private javax.swing.JTabbedPane TabPanEmp;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbEsta;
    private javax.swing.JComboBox<String> cmbEstad;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbMun;
    private javax.swing.JComboBox<String> cmbMuni;
    private javax.swing.ButtonGroup grupTipoU;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    public javax.swing.JLabel jLabel47;
    public javax.swing.JLabel jLabel48;
    public javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel50;
    public javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel52;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    public javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JRadioButton rdbAdmin;
    private javax.swing.JRadioButton rdbOtro;
    private javax.swing.JTextField txtAnuncio;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCall;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtClavH;
    private javax.swing.JTextField txtClaveEmp;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCol;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCp;
    private javax.swing.JTextField txtCu;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtCvee;
    private javax.swing.JTextField txtExt;
    private javax.swing.JTextField txtFe;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtInt;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMun;
    private javax.swing.JTextField txtNomU;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumext;
    private javax.swing.JTextField txtNumint;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
